model_level: 10    # level at which models should be trained. Refer to Data and Model Description document for different model levels
epochs: 50         # number of epochs for training each model. Suggest <50 for quick training on local machine
